from tkinter import *

root = Tk()
root.title("Listbox Testing")
root.geometry("400x400")

#Listbox
listbox = Listbox(root)
#listbox.config(underline=FALSE)
listbox.pack(pady=15)


#add item to LB
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")
listbox.insert(0, "Saturn V")
listbox.insert(1, "Soyuz")
listbox.insert(2, "Delta III")
listbox.insert(3, "Ariane 5")
listbox.insert(4, "Tronador II")
listbox.insert(5, "VLS-1")



root.mainloop()
